In [1]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
data_frame = pd.read_excel('/content/Vitamin_Dataset.xlsx')

In [2]:
#Displays their recorded data values per variable
data_frame.head(10)

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
0,Product Name,Brand Name,Net Contents,Serving Size,Product Type [LanguaL],Supplement Form [LanguaL],Suggested Use
1,B-2 100 mg,Vitamin World,100 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) to two (2..."
2,B-6 100 mg,Vitamin World,250 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
3,C-1000 mg With Protective Bioflavonoids And Wi...,Vitamin World,500 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) to two (2..."
4,Niacin 250 mg,Vitamin World,250 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
5,Niacinamide 500 mg,Vitamin World,100 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
6,Brewer's Yeast,Vitamin World,500 Tablet(s),2 Tablet(s),Other Combinations [A1325],Tablet or Pill [E0155],"DIRECTIONS: For adults, take two (2) tablets t..."
7,Mega B-100,Vitamin World,100 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) caplet da..."
8,Gelatin 650 mg,Vitamin World,250 Rapid Release Capsule(s),2 Capsule(s),Non-Nutrient/Non-Botanical [A1309],Capsule [E0159],"DIRECTIONS: For adults, take two (2) capsules ..."
9,E-Oil,Vitamin World,2.5 fl. Oz.; 74 mL,0.25 mL [5 drops],Vitamin [A1302],Liquid [E0165],"DIRECTIONS: For adults, take five (5) drops (0..."

In [3]:
#Program to print all the column names of the data_frame
list(data_frame.columns)

['Product Name',
 'Brand Name',
 'Net Contents',
 'Serving Size',
 'Product Type ',
 'Supplement Form ',
 'Suggested Use']

In [4]:
#Prints the number of rows and the number of columns
data_frame.shape

(1048575, 7)

In [5]:
#To print the summary of a data_frame that includes the data type of each column
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 7 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Product Name      1048575 non-null  object
 1   Brand Name        1033879 non-null  object
 2   Net Contents      623456 non-null   object
 3   Serving Size      494630 non-null   object
 4   Product Type      507216 non-null   object
 5   Supplement Form   280605 non-null   object
 6   Suggested Use     133571 non-null   object
dtypes: object(7)
memory usage: 56.0+ MB

In [6]:
#Prints descriptive statistics
data_frame.describe()

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
count,1048575,1033879,623456,494630,507216,280605,133571
unique,43017,29927,9626,12196,1601,1915,38331
top,Mega Men,Suggested Use,botanical,100,mg,Capsule [E0159],no
freq,753,50697,106196,20707,242294,26744,63218

In [7]:
#Prints descriptive statistics including only string columns
data_frame.describe(include='object')

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
count,1048575,1033879,623456,494630,507216,280605,133571
unique,43017,29927,9626,12196,1601,1915,38331
top,Mega Men,Suggested Use,botanical,100,mg,Capsule [E0159],no
freq,753,50697,106196,20707,242294,26744,63218

In [8]:
#Finds the number of missing values in the dataset
data_frame.isnull().sum()

Product Name             0
Brand Name           14696
Net Contents        425119
Serving Size        553945
Product Type        541359
Supplement Form     767970
Suggested Use       915004
dtype: int64

In [9]:
#Find the percentage of missing data values per variable
data_frame.isna().sum()/len(data_frame)*100

Product Name         0.000000
Brand Name           1.401521
Net Contents        40.542546
Serving Size        52.828362
Product Type        51.628067
Supplement Form     73.239396
Suggested Use       87.261665
dtype: float64

In [10]:
#Remove duplicate rows
data_frame = data_frame.drop_duplicates()
print("Duplicates removed. New shape:", data_frame.shape)

Duplicates removed. New shape: (718145, 7)

In [11]:
#Displays data with the duplicates removed
data_frame.head(10)

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
0,Product Name,Brand Name,Net Contents,Serving Size,Product Type [LanguaL],Supplement Form [LanguaL],Suggested Use
1,B-2 100 mg,Vitamin World,100 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) to two (2..."
2,B-6 100 mg,Vitamin World,250 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
3,C-1000 mg With Protective Bioflavonoids And Wi...,Vitamin World,500 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) to two (2..."
4,Niacin 250 mg,Vitamin World,250 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
5,Niacinamide 500 mg,Vitamin World,100 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
6,Brewer's Yeast,Vitamin World,500 Tablet(s),2 Tablet(s),Other Combinations [A1325],Tablet or Pill [E0155],"DIRECTIONS: For adults, take two (2) tablets t..."
7,Mega B-100,Vitamin World,100 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) caplet da..."
8,Gelatin 650 mg,Vitamin World,250 Rapid Release Capsule(s),2 Capsule(s),Non-Nutrient/Non-Botanical [A1309],Capsule [E0159],"DIRECTIONS: For adults, take two (2) capsules ..."
9,E-Oil,Vitamin World,2.5 fl. Oz.; 74 mL,0.25 mL [5 drops],Vitamin [A1302],Liquid [E0165],"DIRECTIONS: For adults, take five (5) drops (0..."

In [12]:
#Remove duplicate row
data_frame = data_frame.iloc[1:]
#Print new shape of dataset
data_frame.shape
#Displays dataset wilth removed row
data_frame.head(10)

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
1,B-2 100 mg,Vitamin World,100 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) to two (2..."
2,B-6 100 mg,Vitamin World,250 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
3,C-1000 mg With Protective Bioflavonoids And Wi...,Vitamin World,500 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) to two (2..."
4,Niacin 250 mg,Vitamin World,250 Easy To Swallow Coated Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
5,Niacinamide 500 mg,Vitamin World,100 Tablet(s),1 Tablet(s),Vitamin [A1302],Tablet or Pill [E0155],"DIRECTIONS: For adults, take one (1) tablet da..."
6,Brewer's Yeast,Vitamin World,500 Tablet(s),2 Tablet(s),Other Combinations [A1325],Tablet or Pill [E0155],"DIRECTIONS: For adults, take two (2) tablets t..."
7,Mega B-100,Vitamin World,100 Coated Caplet(s),1 Caplet(s),Other Combinations [A1325],Other (e.g. tea bag) [E0172],"DIRECTIONS: For adults, take one (1) caplet da..."
8,Gelatin 650 mg,Vitamin World,250 Rapid Release Capsule(s),2 Capsule(s),Non-Nutrient/Non-Botanical [A1309],Capsule [E0159],"DIRECTIONS: For adults, take two (2) capsules ..."
9,E-Oil,Vitamin World,2.5 fl. Oz.; 74 mL,0.25 mL [5 drops],Vitamin [A1302],Liquid [E0165],"DIRECTIONS: For adults, take five (5) drops (0..."
10,Creatine Caps 700 mg,Precision Engineered,120 Rapid Release Capsule(s),6 Capsule(s),Non-Nutrient/Non-Botanical [A1309],Capsule [E0159],"DIRECTIONS: For adults, take 6 capsules daily ..."

In [13]:
#To print the summary of a data_frame that includes the data type of each column
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 718144 entries, 1 to 1048574
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Product Name      718144 non-null  object
 1   Brand Name        710256 non-null  object
 2   Net Contents      428181 non-null  object
 3   Serving Size      394289 non-null  object
 4   Product Type      401615 non-null  object
 5   Supplement Form   235489 non-null  object
 6   Suggested Use     117005 non-null  object
dtypes: object(7)
memory usage: 43.8+ MB

In [14]:
#Prints descriptive statistics
data_frame.describe()

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
count,718144,710256,428181,394289,401615,235489,117005
unique,43017,29926,9625,12195,1600,1914,38330
top,"Hair, Skin & Nails",Suggested Use,vitamin,100,mg,Capsule [E0159],no
freq,361,33030,77125,14589,181098,25577,49284

In [15]:
#Prints descriptive statistics including only string columns
data_frame.describe(include='object')

,Product Name,Brand Name,Net Contents,Serving Size,Product Type,Supplement Form,Suggested Use
count,718144,710256,428181,394289,401615,235489,117005
unique,43017,29926,9625,12195,1600,1914,38330
top,"Hair, Skin & Nails",Suggested Use,vitamin,100,mg,Capsule [E0159],no
freq,361,33030,77125,14589,181098,25577,49284

In [16]:
#Finds the number of missing values in the dataset
data_frame.isnull().sum()

Product Name             0
Brand Name            7888
Net Contents        289963
Serving Size        323855
Product Type        316529
Supplement Form     482655
Suggested Use       601139
dtype: int64

In [17]:
#Find the percentage of missing data values per variable
data_frame.isna().sum()/len(data_frame)*100

Product Name         0.000000
Brand Name           1.098387
Net Contents        40.376721
Serving Size        45.096109
Product Type        44.075979
Supplement Form     67.208666
Suggested Use       83.707307
dtype: float64

In [18]:
data_frame['Brand Name'] = data_frame['Brand Name'].fillna('Unknown')
columns_to_fill_empty_string = [
    'Net Contents', 'Serving Size', 'Product Type ',
    'Supplement Form ', 'Suggested Use'
]
for col in columns_to_fill_empty_string:
    data_frame[col] = data_frame[col].fillna('')

print("Null values after filling:")
display(data_frame.isnull().sum())

Null values after filling:

Product Name        0
Brand Name          0
Net Contents        0
Serving Size        0
Product Type        0
Supplement Form     0
Suggested Use       0
dtype: int64

In [19]:
output_file_path = 'Vitamin_Dataset_Cleaned.xlsx'
data_frame.to_excel(output_file_path, index=False)
print(f"Cleaned data saved to {output_file_path}")

Cleaned data saved to Vitamin_Dataset_Cleaned.xlsx

In [20]:
#Load re library to find matching text patterns in the excel file
import re
#Install openpyxl to read the excel file
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [21]:
#Load new dataset and openpyxl library to be able to read the excel file
data_frame = pd.read_excel('/content/Vitamin_Dataset_Cleaned.xlsx', engine='openpyxl')
#Removing white space and characters in columns c.strip for c (for all the columns in the dataset)
data_frame.columns = [c.strip() for c in data_frame.columns]

In [22]:
#Convert written numbers into numeric values by creating a dictionary everything inside of the {} assigns keys to the words giving a value to the corresponding interger like one is 1
word_to_num = {
    'zero':0,'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,
    'eleven':11,'twelve':12,'thirteen':13,'fourteen':14,'fifteen':15,'sixteen':16,'seventeen':17,'eighteen':18,'nineteen':19,'twenty':20
}

In [23]:
#Create dictionary assigning words to numbers
freq_words = {
    'once':1,'one time':1,'one-time':1,
    'twice':2,'two times':2,
    'three times':3,
    'four times':4,
    'five times':5,
    'six times':6,
}

In [24]:
#Assigning types of supplements to columns
data_frame['is_botanical'] = data_frame['Product Type'].str.contains('botanical')
data_frame['is_vitamin'] = data_frame['Product Type'].str.contains('vitamin')
data_frame['is_mineral'] = data_frame['Product Type'].str.contains('mineral')
#bitwise| for other combination or multi
data_frame['is_combination'] = data_frame['Product Type'].str.contains('other combinations') | data_frame['Product Type'].str.contains('multi')

In [25]:
#Assigning forms of supplements to columns
form = data_frame['Supplement Form'].fillna('').str.lower()
data_frame['is_liquid'] = form.str.contains('liquid')
data_frame['is_capsule'] = form.str.contains('capsule')
data_frame['is_tablet'] = form.str.contains('tablet|caplet|lozenge|wafer')
#bitwise | for different forms if not these forms ignore
fd_powder_re = re.compile(r'powder|granules|crystals', re.IGNORECASE)
#if the text value lambda is true or false
data_frame['is_powder'] = form.apply(lambda x: bool(fd_powder_re.search(x)) if isinstance(x, str) else False)

In [26]:
#Replacing missing values with an empty string and converting all words to lowercase
text = data_frame['Suggested Use'].fillna('').str.lower()
#Assigning these values to a column
data_frame['mentions_bedtime'] = text.str.contains('bedtime')
data_frame['mentions_caffeine'] = text.str.contains('caffeine')
data_frame['mentions_empty_stomach'] = text.str.contains('empty stomach')
data_frame['mentions_shake_well'] = text.str.contains('shake well')
data_frame['mentions_refrigerate'] = text.str.contains('refrigerate')
#Calculates how complex direction to take supplements are taking into account all these factors axis 1 means to run data row by row
data_frame['direction_complexity_score'] = (
    data_frame[['mentions_bedtime','mentions_caffeine','mentions_empty_stomach','mentions_shake_well','mentions_refrigerate']]
    .sum(axis=1)
)

In [27]:
#True or False list for all these types of supplements
def make_label(row):
    labels = []
    if row.get('is_vitamin'): labels.append('Vitamin')
    if row.get('is_mineral'): labels.append('Mineral')
    if row.get('is_botanical'): labels.append('Botanical')
    if row.get('is_combination'): labels.append('Combo')
    #if it is multiple its combined with a /
    form_bits = []
    if row.get('is_liquid'): form_bits.append('Liquid')
    if row.get('is_capsule'): form_bits.append('Capsule')
    if row.get('is_tablet'): form_bits.append('Tablet/Caplet/Lozenge')
    if row.get('is_powder'): form_bits.append('Powder')
    if form_bits:
        labels.append('/'.join(form_bits))
    if row.get('mentions_bedtime'): labels.append('Bedtime')
    if row.get('mentions_caffeine'): labels.append('Caffeine')
    if row.get('mentions_empty_stomach'): labels.append('Empty stomach')
    if row.get('mentions_shake_well'): labels.append('Shake well')
    if row.get('mentions_refrigerate'): labels.append('Refrigerate')
    #seperated with commas
    return ', '.join(labels)

In [28]:
#Creating a rule label to be applied to every row
data_frame['rule_label'] = data_frame.apply(make_label, axis=1)

preview = data_frame[['Product Name','Brand Name','Serving Size','Suggested Use','rule_label','direction_complexity_score']].copy()

In [29]:
# Making sure text is clean
data_frame['suggested_use_clean'] = data_frame['Suggested Use'].fillna('').str.lower()

In [30]:
def parse_dose_frequency(text):
    dose_min = dose_max = freq = None

    if not isinstance(text, str):
        return pd.Series([None, None, None])

    #Dose range (e.g. 1-2 tablets)
    m = re.search(r'(\d+(?:\.\d+)?)\s*(?:to|-|–)\s*(\d+(?:\.\d+)?)\s*(tablet|capsule|softgel|drop|ml|g)', text)
    if m:
        dose_min = float(m.group(1))
        dose_max = float(m.group(2))
    else:
        #Single dose (e.g. 1 tablet)
        m2 = re.search(r'(\d+(?:\.\d+)?)\s*(tablet|capsule|softgel|drop|ml|g)', text)
        if m2:
            dose_min = dose_max = float(m2.group(1))

    #Frequency (e.g. 2 times daily)
    m3 = re.search(r'(\d+(?:\.\d+)?)\s*(times?|x)\s*(a day|daily)', text)
    if m3:
        freq = float(m3.group(1))

    #Word-based frequency (twice daily)
    if freq is None:
        if "once" in text:
            freq = 1
        elif "twice" in text:
            freq = 2
        elif "three times" in text:
            freq = 3

    return pd.Series([dose_min, dose_max, freq])

In [31]:
#apply
data_frame[['dose_min', 'dose_max', 'frequency_per_day']] = data_frame['suggested_use_clean'].apply(parse_dose_frequency)

In [32]:
def extract_directions(text):
    if not isinstance(text, str):
        return pd.Series([None]*8)

    return pd.Series([
        bool(re.search(r'morning', text)),
        bool(re.search(r'evening|night', text)),
        bool(re.search(r'bedtime', text)),
        bool(re.search(r'with food|with a meal|after meals', text)),
        bool(re.search(r'empty stomach|before meals', text)),
        bool(re.search(r'caffeine', text)),
        bool(re.search(r'do not exceed|max dose', text)),
        bool(re.search(r'consult.*doctor|physician', text))
    ])

In [33]:
data_frame[[
    'morning', 'evening', 'bedtime',
    'with_food', 'empty_stomach',
    'caffeine_warning', 'max_warning', 'consult_doctor'
]] = data_frame['suggested_use_clean'].apply(extract_directions)

In [34]:
def assign_time(row):
    if row['bedtime']:
        return 'bedtime'
    elif row['morning']:
        return 'morning'
    elif row['evening']:
        return 'evening'
    else:
        return 'anytime'

data_frame['recommended_time'] = data_frame.apply(assign_time, axis=1)

In [35]:
def create_label(row):
    labels = []

    if row['morning']: labels.append("Morning")
    if row['evening']: labels.append("Evening")
    if row['bedtime']: labels.append("Bedtime")
    if row['with_food']: labels.append("With food")
    if row['empty_stomach']: labels.append("Empty stomach")
    if row['caffeine_warning']: labels.append("Avoid caffeine")
    if row['max_warning']: labels.append("Max limit warning")

    return ", ".join(labels)

data_frame['rule_label'] = data_frame.apply(create_label, axis=1)

In [36]:
data_frame['daily_dose_min'] = data_frame['dose_min'] * data_frame['frequency_per_day']
data_frame['daily_dose_max'] = data_frame['dose_max'] * data_frame['frequency_per_day']

In [37]:
data_frame[[
    'Suggested Use',
    'dose_min', 'dose_max',
    'frequency_per_day',
    'recommended_time',
    'rule_label'
]].head(10)

,Suggested Use,dose_min,dose_max,frequency_per_day,recommended_time,rule_label
0,"DIRECTIONS: For adults, take one (1) to two (2...",NaN,NaN,NaN,anytime,With food
1,"DIRECTIONS: For adults, take one (1) tablet da...",NaN,NaN,NaN,anytime,With food
2,"DIRECTIONS: For adults, take one (1) to two (2...",NaN,NaN,NaN,anytime,
3,"DIRECTIONS: For adults, take one (1) tablet da...",NaN,NaN,NaN,anytime,With food
4,"DIRECTIONS: For adults, take one (1) tablet da...",NaN,NaN,NaN,anytime,With food
5,"DIRECTIONS: For adults, take two (2) tablets t...",NaN,NaN,3.0,anytime,
6,"DIRECTIONS: For adults, take one (1) caplet da...",NaN,NaN,NaN,anytime,With food
7,"DIRECTIONS: For adults, take two (2) capsules ...",NaN,NaN,NaN,bedtime,Bedtime
8,"DIRECTIONS: For adults, take five (5) drops (0...",0.25,0.25,NaN,anytime,With food
9,"DIRECTIONS: For adults, take 6 capsules daily ...",6.00,6.00,NaN,anytime,

In [38]:
output_excel = 'Vitamin_RuleModel_Output.xlsx'

# Ensure preview_sorted is defined before saving if it's not already.
# If it is already defined from a previous execution, this will just re-sort.
if 'preview' in globals():
    preview_sorted = preview.sort_values(by='direction_complexity_score', ascending=False)
else:
    print("Warning: 'preview' DataFrame not found. Cannot create 'preview_sorted'.")
    preview_sorted = pd.DataFrame() # Create an empty DataFrame to avoid errors


with pd.ExcelWriter(output_excel, engine='openpyxl') as writer:
    data_frame.to_excel(writer, sheet_name='enriched', index=False)
    if not preview_sorted.empty:
        preview_sorted.to_excel(writer, sheet_name='top_daily_units', index=False)

print(f"All changes saved to {output_excel}")

All changes saved to Vitamin_RuleModel_Output.xlsx